import fsp from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { regenerateDoc, fallbackRewriter } from "../../../../core/src/tools/regenerate-doc";

const temporaryProjects: string[] = [];

async function makeProject(): Promise<string> {
  const projectPath = await fsp.mkdtemp(path.join(os.tmpdir(), "docuflow-watch-"));
  temporaryProjects.push(projectPath);
  
  const sourcesDir = path.join(projectPath, ".docuflow", "sources");
  await fsp.mkdir(sourcesDir, { recursive: true });
  
  return projectPath;
}

afterEach(async () => {
  await Promise.all(temporaryProjects.splice(0).map((projectPath) =>
    fsp.rm(projectPath, { recursive: true, force: true })
  ));
});

describe("watch code sync", () => {
  it("automatically regenerates doc and ingests when a code file changes that the doc cites", async () => {
    const projectPath = await makeProject();
    
    // Create source code that triggers the detectDrift stub (roles: string[])
    const codePath = path.join(projectPath, "src/auth.ts");
    await fsp.mkdir(path.dirname(codePath), { recursive: true });
    await fsp.writeFile(codePath, "export interface User { roles: string[]; }", "utf8");
    
    // Create doc that cites the code file and has the stale text (role: string)
    const docPath = path.join(projectPath, ".docuflow", "sources", "auth_doc.md");
    await fsp.writeFile(docPath, [
      "---",
      "tags: [\"auth\"]",
      "sources: [\"auth-design\"]",
      "owner: \"platform-team\"",
      "---",
      "# Auth Documentation",
      "> CLAIM[code:src/auth.ts#User] (feature): user has a role.",
      "The user object has `role: string`.",
      ""
    ].join("\n"), "utf8");
    
    // Ensure the core tools are built (already done via npm run build before tests)
    
    // Call the newly deterministic watch loop function
    await regenerateDoc({ project_path: projectPath, doc_path: ".docuflow/sources/auth_doc.md", code_paths: ["src/auth.ts"] }, { rewriteDocument: fallbackRewriter });
    
    // Assert on the wiki file's content (regenerated by localRewriteStub)
    const newContent = await fsp.readFile(docPath, "utf8");
    expect(newContent).toContain("updated_by: docuflow-doc-regeneration");
    expect(newContent).toContain("roles: string[]");
    
    // Assert curated keys SURVIVE regeneration
    expect(newContent).toContain("tags: [\"auth\"]");
    expect(newContent).toContain("sources: [\"auth-design\"]");
    expect(newContent).toContain("owner: \"platform-team\"");
    
    // Assert exactly one Auto-Generated Updates section
    const occurrences = (newContent.match(/## Auto-Generated Updates/g) || []).length;
    expect(occurrences).toBe(1);
    
    // Run second time to ensure idempotence
    await regenerateDoc({ project_path: projectPath, doc_path: ".docuflow/sources/auth_doc.md", code_paths: ["src/auth.ts"] }, { rewriteDocument: fallbackRewriter });
    const newContent2 = await fsp.readFile(docPath, "utf8");
    const occurrences2 = (newContent2.match(/## Auto-Generated Updates/g) || []).length;
    expect(occurrences2).toBe(1);

    
  });
});
